### ISSUE TITLE
Question sections?

### ISSUE THREAD

**Issue by gibson042** [dns-stats/draft-dns-capture-format#17]
Various points in the text reference "second and subsequent question sections". What does this mean? Obviously, any given DNS message includes exactly one [question section](https://tools.ietf.org/html/rfc1035#section-4.1.2), containing any number of entries (but almost always 1).

**Comment by banburybill** [comment]
The basic unit of query/response data always includes data from the first question, if present. Recording data from RRs is optional; if enabled for questions, we already have the data from the first question, hence the optional data recorded is for second and subsequent questions.

While queries with no question, or with more than one question, don't make much sense, they are well-formed DNS messages, and I have seen examples of both in traffic captures.

**Comment by gibson042** [comment]
While any DNS message can include an arbitrary number of questions, it necessary includes only a single question _section_. This has been improved in -01 by the more accurate "second and subsequent Questions of any Question section", but instances of the old text still remain.

**Comment by banburybill** [comment]
Apologies. I get what you mean now. I'll fix the remaining instances of the old text.
