### ISSUE TITLE
Clarify handling for XFR and DSO messages

### ISSUE THREAD

**Issue by saradickinson** [dns-stats/draft-dns-capture-format#39]
Need to outline choices wrt handling messages that are well-formed but cannot or should not be stored in the C-DNS.
We should probably add a 'ignore-opcodes' filter option to handle DSO?

**Comment by banburybill** [comment]
Adding a 'ignore opcodes' filter seems like a plan.

Though I guess we should also add a means to record TLV content? Prima facie, this isn't difficult; an optional tlv item in QueryResponseExtended. 

Though there is an interesting question on how you tell when TLV ends and trailing data begins.

**Comment by banburybill** [comment]
Further discussion of DSO in #42.

**Comment by banburybill** [comment]
Placeholder section in implementation guidelines.
