### ISSUE TITLE
Additional flags

### ISSUE THREAD

**Issue by saradickinson** [dns-stats/draft-dns-capture-format#40]
Proposed:
- data is anonymised flag
- data is sampled flag

**Comment by banburybill** [comment]
Do we anticipate this being a per-data-item flag or a per-collection thing?

My initial naive assumption is that these flags would apply to all data in a particular collection. They could conceivably be configuration flags (i.e. 'collection tool instructed to anonymise data', 'collection tool instructed to sample data'). In the case of sampling, I imagine some details of how the sampling was to be carried out would be required. Every nth query or every n (micro|milli?)seconds?

It occurs to me they could also tag individual query-response items.

**Comment by banburybill** [comment]
Added, with question about further description.
