### ISSUE TITLE
Increase timestamp resolution

### ISSUE THREAD

**Issue by banburybill** [dns-stats/draft-dns-capture-format#7]
Jerry Lundström <jerry@dns-oarc.net>,
Message-ID: <ef56163f-0c5a-c934-4a37-9a83c2d8386e@dns-oarc.net>

On 11/01/16 16:20, Sara Dickinson wrote:
>> On 1 Nov 2016, at 08:12, Jerry Lundström <jerry@dns-oarc.net
>> "Timestamp" in "Block preamble map" is limited to microseconds, maybe
>> add that each element within the array after the first is a /million to
>> also allow nano/pico?
>
> That seems reasonable, if it can be done in a flexible way where the
> additional resolution is only written when needed (i.e when not 0) so as
> to not increase file size unnecessarily. 

That was kinda the point:

  [ seconds [, optional microseconds [, optional picoseconds ] ] ]

**Comment by banburybill** [comment]
Stick with microseconds being compulsory, and add optional picoseconds.

**Comment by saradickinson** [comment]
Done in -01 version
