### ISSUE TITLE
Add further discussion of malformed packets and propose a mechanism for recording them

### ISSUE THREAD

**Issue by banburybill** [dns-stats/draft-dns-capture-format#9]
Recording mechanism should be proposed for comment before any implementation.

**Comment by banburybill** [comment]
I am inclined to a separate block table malformed-packets, containing timestamp and raw packet data, rather than adding it as alternate content for query/responses.

This keeps similar query/response data together for easier compression. Potentially raw packets are also similar.

**Comment by saradickinson** [comment]
Done in -01 version - need feedback on having placeholder records

**Comment by banburybill** [comment]
Updated malformed packet discussion and posed question.
